### PR TITLE
Make compatible with fluentd v0.14+

### PR DESCRIPTION
**Pull request by spackle0**
- fluentd now requires router.emit instead of Engine.emit

### CODE REVIEW

**Comment by repeatedly** [comment]
Could you follow DCO? https://github.com/apps/dco

**Comment by spackle0** [comment]
Let me read that and modify. 
I'm actually trying to duplicate 5928322ce396ac96c31394c6fa4ea1a37c93b269 since this plugin doesn't work with the latest fluentd (and I need it to) and the author of that commit has not responded to your request in their PR.

**Comment by spackle0** [comment]
> Could you follow DCO? https://github.com/apps/dco

Done.

**Comment by spackle0** [comment]
Have to redo.

**Pull request closed without merging**
